exclude:
  - Gemfile
  - Gemfile.lock
  - Session.vim
  - bower.json
  - gulpfile.js
  - package.json
  - bower_components/
  - node_modules/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

